### ISSUE TITLE
Error on pages 74-75

### ISSUE THREAD

**Issue by KulaGGin** [PacktPublishing/Mastering-Windows-Presentation-Foundation-Second-Edition#1]
Reading your book, Sheridan. It's great so far. Thank you. After reading intro C# book(HeadFirst C#) and trying out quite a few intermediate books and courses about developing more complex applications with MVVM, I think your book is the one.

I think I spotted a mistake and want to report it.

On pages 74-75 you present BaseVisibilityConverter class:
![FoxitReader_wgcXiSOKXB](https://user-images.githubusercontent.com/16989713/81282335-b1f4e480-9063-11ea-802d-556aad360009.png)

```
using System.Windows;
using System.Windows.Data;
namespace CompanyName.ApplicationName.Converters {
    public abstract class BaseVisibilityConverter {
        public enum FalseVisibility { Hidden, Collapsed }
        protected Visibility FalseVisibilityValue { get; set; } =
            Visibility.Collapsed;
        public FalseVisibility FalseVisibilityState {
            get {
                return FalseVisibilityState == Visibility.Collapsed ?
                           FalseVisibility.Collapsed : FalseVisibility.Hidden;
            }
            set {
                FalseVisibilityState = value == FalseVisibility.Collapsed ?
                                           Visibility.Collapsed : Visibility.Hidden;
            }
        }
        public bool IsInverted { get; set; }
    }
}
```

When I paste that in Visual Studio, it throws errors:
![devenv_gKa7qyN2r4](https://user-images.githubusercontent.com/16989713/81282550-fbddca80-9063-11ea-8c3e-e1f89d750f91.png)

And if I paste the code from GitHub project: https://github.com/PacktPublishing/Mastering-Windows-Presentation-Foundation-Second-Edition/blob/master/CompanyName.ApplicationName.Converters/BaseVisibilityConverter.cs

It doesn't throw any errors. In GitHub project FalseVisibilityState property uses FalseVisibilityValue and in the book FalseVisibilityState property uses itself.

**Comment by SheridanYuen** [comment]
After looking into your issue, I can see that it is only caused because of the new lines in the book. You simply need to put the code for each getter onto single lines for them to work.

**Comment by KulaGGin** [comment]
Even when I put get and set on the same line, nothing changes:
![devenv_xE9YM89rxI](https://user-images.githubusercontent.com/16989713/81286336-912f8d80-9069-11ea-81b5-a979b5c3de60.png)

On the next page in the book it even says:
> Users can set the FalseVisibilityState property when using the control and this sets
the protected FalseVisibilityValue property internally.

But in the code in the book we can see that FalseVisibilityState does not set protected FalseVisibilityValue property internally. It sets itself:
![ShareX_9ETvdJ5Hup](https://user-images.githubusercontent.com/16989713/81286450-c2a85900-9069-11ea-857f-69bb8ec634d4.png)

And as I mentioned before, it's fixed in the code on this Github repository and FalseVisibilityState sets FalseVisibilityValue as intended:
![devenv_f47hMAKLbl](https://user-images.githubusercontent.com/16989713/81286625-0a2ee500-906a-11ea-9d3d-28ce81443998.png)

**Comment by SheridanYuen** [comment]
My apologies. You are correct. 
Somehow, the code in the book was updated incorrectly. In the getter and setter, FalseVisibilityValue has been mistakenly replaced by FalseVisibilityState. 
I have fixed this now and the next publication will contain the correction. 
Many thanks and kind regards,
Sheridan
