### ISSUE TITLE
DisabledTooltip example in Attaching properties paragraph doesn't work

### ISSUE THREAD

**Issue by KulaGGin** [PacktPublishing/Mastering-Windows-Presentation-Foundation-Second-Edition#2]
On pages 243-245 in the Attaching properties paragraph, you provide an example with the DisabledTooltip attached property.

I can't make it to work. When I disable the button, it's supposed to show "You must correct validation errors before saving", but instead it still shows "Saves the user" tooltip:
![E0gk0yl2S3](https://user-images.githubusercontent.com/16989713/84378639-2ab00900-abed-11ea-8688-03bc753b947c.png)

Not sure if I missed something or the example just doesn't work. I don't think this specific example is in the example files. Here's my solution with this example: https://github.com/KulaGGin/MasteringWPF/tree/DisabledToolTipDoesntWork

It's on the DisabledToolTipDoesntWork branch.

Please, let me know how to make it work.

**Comment by SheridanYuen** [comment]
Apologies. You seem to have the version from the first edition, that ran on a different Framework version. For the second edition, you'll need to replace your OnDisabledToolTipChanged method with this one:

private static void OnDisabledToolTipChanged(DependencyObject dependencyObject, DependencyPropertyChangedEventArgs e)
{
    Button button = dependencyObject as Button;
    ToolTipService.SetShowOnDisabled(button, true);
    string oldValue = (string)e.OldValue, newValue = (string)e.NewValue;
    if (oldValue.Length == 0 && newValue.Length > 0) button.IsEnabledChanged += Button_IsEnabledChanged;
    else if (oldValue.Length > 0 && newValue.Length == 0) button.IsEnabledChanged -= Button_IsEnabledChanged;
}

I will ensure that this is updated for the upcoming publication.

**Comment by KulaGGin** [comment]
Thanks, it works now.

> You seem to have the version from the first edition, that ran on a different Framework version.

On the first page of the book, it says that it's the second edition.

**Comment by SheridanYuen** [comment]
I think you misunderstood my comment. I meant that you seem to have had the version of this code excerpt from the first edition, rather than the one that I sent you, from the second edition. I have now updated the second edition with the correct code. Thank you.
